version: "3.7"

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    command: go run main.go
    ports:
      - 8000:8000
    working_dir: /go/src/app
    environment:
      DBMS: postgres
      HOST: postgres
      PORT: 5432
      USER: plumber
      DBNAME: plumber
      PASSWORD: HAUcf&-LrHu?[/J5

  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgres
    environment:
      LANG: ja_JP.utf8
      POSTGRES_USER: plumber
      POSTGRES_DB: plumber
      POSTGRES_PASSWORD: HAUcf&-LrHu?[/J5
      TZ: Asia/Tokyo

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis


volumes:
  postgres:
  redis: