version: "3.7"

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  app:
    image: alpine
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: ./main
    working_dir: /app/bin

  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: "Asia/Tokyo"

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis


volumes:
  postgres:
  redis: